let currentContent=null;function buildBreadcrumb(contentKey){const breadcrumbNav=document.getElementById('breadcrumb');const breadcrumbList=breadcrumbNav.querySelector('ol');breadcrumbList.innerHTML='';const homeCrumb=document.createElement('li');homeCrumb.setAttribute('itemprop','itemListElement');homeCrumb.setAttribute('itemscope','');homeCrumb.setAttribute('itemtype','https://schema.org/ListItem');const firstNavItem=getFirstNavigationItem();const isFirstNavItem=contentKey===firstNavItem;if(isFirstNavItem){const firstNavLink=document.querySelector('#sidebar .nav-level-1 > li:first-child a[data-content]');const pageName=firstNavLink?firstNavLink.textContent.trim():'Home';homeCrumb.innerHTML=`
            <span itemprop="name">${pageName}</span>
            <meta itemprop="position" content="1">
        `;}else{const firstNavLink=document.querySelector('#sidebar .nav-level-1 > li:first-child a[data-content]');const pageName=firstNavLink?firstNavLink.textContent.trim():'Home';homeCrumb.innerHTML=`
            <a href="#" data-content="${firstNavItem}" itemprop="item">
                <span itemprop="name">${pageName}</span>
            </a>
            <meta itemprop="position" content="1">
        `;}
breadcrumbList.appendChild(homeCrumb);const currentLink=document.querySelector(`[data-content="${contentKey}"]`);if(!currentLink)return;const path=[];let element=currentLink;while(element){if(element.dataset&&element.dataset.content){path.unshift({key:element.dataset.content,text:element.textContent.trim()});}
const parentUl=element.closest('ul');if(!parentUl||parentUl.classList.contains('nav-level-1'))break;const parentLi=parentUl.parentElement;if(!parentLi||!parentLi.classList.contains('has-children'))break;element=parentLi.querySelector('.nav-item-wrapper > a');}
let position=2;const startIndex=path[0]?.key===firstNavItem?1:0;for(let i=startIndex;i<path.length;i++){const item=path[i];const li=document.createElement('li');li.setAttribute('itemprop','itemListElement');li.setAttribute('itemscope','');li.setAttribute('itemtype','https://schema.org/ListItem');if(i===path.length-1){li.innerHTML=`
                <span itemprop="name">${item.text}</span>
                <meta itemprop="position" content="${position}">
            `;}else{li.innerHTML=`
                <a href="#" data-content="${item.key}" itemprop="item">
                    <span itemprop="name">${item.text}</span>
                </a>
                <meta itemprop="position" content="${position}">
            `;}
breadcrumbList.appendChild(li);position++;}
breadcrumbList.querySelectorAll('a[data-content]').forEach(link=>{link.addEventListener('click',function(e){e.preventDefault();loadContent(this.dataset.content);expandToActiveItem(this.dataset.content);});});}
function enhanceTOCWithNavigation(tocElement,contentKey){const tocHeaderLeft=tocElement.querySelector('.toc-header-left > ul');if(!tocHeaderLeft){return;}
if(tocHeaderLeft.querySelector('.toc-section[data-section="navigation"]')){return;}
const currentLink=document.querySelector(`[data-content="${contentKey}"]`);if(!currentLink){return;}
const parentLi=currentLink.closest('li.has-children');if(!parentLi){return;}
const childList=parentLi.querySelector(':scope > ul.nav-level-2, :scope > ul.nav-level-3, :scope > ul.nav-level-4');if(!childList){return;}
const navItems=[];const processNavItem=(li,level=1)=>{const link=li.querySelector(':scope > a, :scope > .nav-item-wrapper > a');if(!link)return null;const childKey=link.dataset.content;const childText=link.textContent.trim();if(childKey===contentKey){return null;}
const item={text:childText,href:`#${childKey}`,dataContent:childKey,level:level,children:[]};const hasChildren=li.classList.contains('has-children');if(hasChildren){const childUl=li.querySelector(':scope > ul');if(childUl){const childLis=childUl.querySelectorAll(':scope > li');childLis.forEach(childLi=>{const childItem=processNavItem(childLi,level+1);if(childItem){item.children.push(childItem);}});}}
return item;};const topLevelItems=childList.querySelectorAll(':scope > li');topLevelItems.forEach(li=>{const item=processNavItem(li);if(item){navItems.push(item);}});if(navItems.length===0){return;}
const hasHeadings=tocElement.querySelector('.toc-section[data-section="headings"]');const isCollapsed=hasHeadings;const buildNavHTML=items=>{let html='';items.forEach(item=>{const className=item.level>1?`toc-item-level-${item.level}`:'';html+=`<li class="${className}"><a href="${item.href}" data-content="${item.dataContent}">${item.text}</a>`;if(item.children.length>0){html+='<ul>'+buildNavHTML(item.children)+'</ul>';}
html+='</li>';});return html;};const navSection=document.createElement('li');navSection.className='toc-section';navSection.innerHTML=`
    <div class="toc-section-header">
      <button class="toc-section-toggle" data-section="navigation">${isCollapsed ? '▶' : '▼'}</button>
      <span class="toc-section-title">Navigation</span>
    </div>
    <ul class="toc-section-content" data-section="navigation"${isCollapsed ? ' style="display: none;"' : ''}>
      ${buildNavHTML(navItems)}
    </ul>
  `;tocHeaderLeft.appendChild(navSection);const toggleBtn=navSection.querySelector('.toc-section-toggle');toggleBtn.addEventListener('click',()=>{const section=navSection.querySelector('.toc-section-content');const isHidden=section.style.display==='none';section.style.display=isHidden?'':'none';toggleBtn.textContent=isHidden?'▼':'▶';});}
function generateTableOfContents(contentKey,htmlContent){let tocItems=[];const currentLink=document.querySelector(`[data-content="${contentKey}"]`);if(currentLink){const parentLi=currentLink.closest('li.has-children');if(parentLi){const childList=parentLi.querySelector(':scope > ul.nav-level-2, :scope > ul.nav-level-3, :scope > ul.nav-level-4');if(childList){const processNavItem=li=>{const link=li.querySelector(':scope > a, :scope > .nav-item-wrapper > a');if(!link)return null;const childKey=link.dataset.content;const childText=link.textContent.trim();const hasChildren=li.classList.contains('has-children');if(childKey===contentKey){if(hasChildren){const childUl=li.querySelector(':scope > ul');if(childUl){const childLis=childUl.querySelectorAll(':scope > li');const childItems=[];childLis.forEach(childLi=>{const childItem=processNavItem(childLi);if(childItem){childItems.push(childItem);}});return childItems;}}
return null;}
const item={type:'subpage',text:childText,href:`#${childKey}`,dataContent:childKey,children:[]};if(hasChildren){const childUl=li.querySelector(':scope > ul');if(childUl){const childLis=childUl.querySelectorAll(':scope > li');childLis.forEach(childLi=>{const childItem=processNavItem(childLi);if(childItem){if(Array.isArray(childItem)){item.children.push(...childItem);}else{item.children.push(childItem);}}});}}
return item;};const topLevelItems=childList.querySelectorAll(':scope > li');topLevelItems.forEach(li=>{const item=processNavItem(li);if(item){if(Array.isArray(item)){tocItems.push(...item);}else{tocItems.push(item);}}});}}}
const tempDiv=document.createElement('div');tempDiv.innerHTML=htmlContent;const headings=tempDiv.querySelectorAll('h2, h3, h4');const headingItems=[];let currentH2=null;let currentH3=null;const generateHeadingId=(text,index)=>{let id=text.toLowerCase().replace(/[^\w\s-]/g,'').replace(/\s+/g,'-').replace(/--+/g,'-').replace(/^-+|-+$/g,'');if(!id||id.length<2){id=`heading-${index}`;}
return id;};headings.forEach((heading,index)=>{const headingText=heading.textContent.trim();if(headingText.endsWith(':')){return;}
const headingId=generateHeadingId(headingText,index);const level=heading.tagName.toLowerCase();const item={type:'heading',level:level,text:headingText,href:`#${contentKey}:${headingId}`,id:headingId,children:[]};if(level==='h2'){headingItems.push(item);currentH2=item;currentH3=null;}else if(level==='h3'){if(currentH2){currentH2.children.push(item);}else{headingItems.push(item);}
currentH3=item;}else if(level==='h4'){if(currentH3){currentH3.children.push(item);}else if(currentH2){currentH2.children.push(item);}else{headingItems.push(item);}}});const allTocItems=[...headingItems,...tocItems];if(allTocItems.length===0)return null;const buildTocItem=(item,isTopLevel=false)=>{const hasChildren=item.children&&item.children.length>0;const isHeading=item.type==='heading';let html='<li class="';if(item.type==='subpage'){html+='toc-subpage';}else if(item.level==='h2'){html+='toc-h2';}else if(item.level==='h3'){html+='toc-h3';}else if(item.level==='h4'){html+='toc-h4';}
if(hasChildren&&isHeading){html+=' toc-item';}
html+='">';if(item.type==='subpage'){html+=`<a href="${item.href}" data-content="${item.dataContent}">${item.text}</a>`;}else{if(hasChildren&&isHeading){html+='<div class="toc-item-wrapper">';}
html+=`<a href="${item.href}">${item.text}</a>`;if(hasChildren&&isHeading){html+='</div>';}}
if(hasChildren&&isHeading){html+='<ul class="toc-children">';item.children.forEach(child=>{html+=buildTocItem(child,false);});html+='</ul>';}else if(hasChildren&&item.type==='subpage'){html+='<ul class="toc-children" style="max-height: none;">';item.children.forEach(child=>{html+=buildTocItem(child,false);});html+='</ul>';}
html+='</li>';return html;};let tocHtml='<div class="table-of-contents">';tocHtml+='<div class="toc-header">';tocHtml+='<div class="toc-header-left">';tocHtml+='<ul>';let hasHeadings=headingItems.length>0;let hasNavigation=tocItems.length>0;if(hasHeadings){tocHtml+='<li class="toc-section">';tocHtml+='<div class="toc-section-header">';tocHtml+='<button class="toc-section-toggle" data-section="headings">▼</button>';tocHtml+='<span class="toc-section-title">Contents</span>';tocHtml+='</div>';tocHtml+='<ul class="toc-section-content" data-section="headings">';headingItems.forEach(item=>{tocHtml+=buildTocItem(item,true);});tocHtml+='</ul>';tocHtml+='</li>';}
if(hasHeadings&&hasNavigation){tocHtml+='<li class="toc-divider"></li>';}
if(hasNavigation){let navigationClass=hasHeadings?'collapsed':'';tocHtml+=`<li class="toc-section ${navigationClass}">`;tocHtml+='<div class="toc-section-header">';tocHtml+='<button class="toc-section-toggle" data-section="navigation">▼</button>';tocHtml+='<span class="toc-section-title">Navigation</span>';tocHtml+='</div>';tocHtml+='<ul class="toc-section-content" data-section="navigation">';tocItems.forEach(item=>{tocHtml+=buildTocItem(item,true);});tocHtml+='</ul>';tocHtml+='</li>';}
tocHtml+='</ul>';tocHtml+='</div>';tocHtml+='<div class="toc-header-right">';tocHtml+='<button class="toc-toggle" aria-label="Toggle table of contents">▼</button>';tocHtml+='</div>';tocHtml+='</div>';tocHtml+='</div>';return{html:tocHtml,headingIds:headingItems.flatMap(item=>{const ids=item.id?[item]:[];if(item.children){ids.push(...item.children.filter(c=>c.id));}
return ids;})};}
function updatePageMetadata(contentKey,contentDiv){const mainHeading=contentDiv.querySelector('h2');const pageTitle=mainHeading?mainHeading.textContent.trim():formatPageTitle(contentKey);const firstParagraph=contentDiv.querySelector('p');const description=firstParagraph?firstParagraph.textContent.trim().substring(0,160)+'...':'Welcome to GAZ Tank. Explore our content and resources.';document.title=`${pageTitle} - GAZ Tank`;let metaDescription=document.querySelector('meta[name="description"]');if(metaDescription){metaDescription.setAttribute('content',description);}
let ogTitle=document.querySelector('meta[property="og:title"]');if(ogTitle){ogTitle.setAttribute('content',`${pageTitle} - GAZ Tank`);}
let ogDescription=document.querySelector('meta[property="og:description"]');if(ogDescription){ogDescription.setAttribute('content',description);}
let ogUrl=document.querySelector('meta[property="og:url"]');if(ogUrl){ogUrl.setAttribute('content',`https://mygaztank.com/#${contentKey}`);}
let twitterTitle=document.querySelector('meta[name="twitter:title"]');if(twitterTitle){twitterTitle.setAttribute('content',`${pageTitle} - GAZ Tank`);}
let twitterDescription=document.querySelector('meta[name="twitter:description"]');if(twitterDescription){twitterDescription.setAttribute('content',description);}
let twitterUrl=document.querySelector('meta[name="twitter:url"]');if(twitterUrl){twitterUrl.setAttribute('content',`https://mygaztank.com/#${contentKey}`);}
let canonical=document.querySelector('link[rel="canonical"]');if(canonical){canonical.setAttribute('href',`https://mygaztank.com/#${contentKey}`);}}
function formatPageTitle(contentKey){return contentKey.split('_').map(word=>word.charAt(0).toUpperCase()+word.slice(1)).join(' ');}
function displayHashtags(contentElement){const hashtagArea=document.getElementById('hashtag-area');hashtagArea.innerHTML='';const taggedElement=contentElement.querySelector('[data-hashtags]');if(taggedElement){const tagsAttr=taggedElement.getAttribute('data-hashtags');if(tagsAttr&&tagsAttr.trim()){const tags=tagsAttr.split(',').map(tag=>tag.trim()).filter(tag=>tag);tags.forEach(tag=>{const hashtagSpan=document.createElement('span');hashtagSpan.className='hashtag';hashtagSpan.textContent='#'+tag;hashtagArea.appendChild(hashtagSpan);});}}}
function enableLazyLoading(){const pageContent=document.getElementById('page-content');const images=pageContent.querySelectorAll('img');images.forEach(img=>{if(img.hasAttribute('data-no-lazy')||img.classList.contains('no-lazy')||img.getAttribute('loading')==='eager'){return;}
if(!img.hasAttribute('loading')){img.setAttribute('loading','lazy');}
if(!img.style.maxWidth){img.style.maxWidth='100%';img.style.height='auto';}});}
async function loadContent(contentKey,saveToStorage=true,updateHash=true){const pageContent=document.getElementById('page-content');if(currentContent===contentKey){return;}
try{const response=await fetch(`content/${contentKey}.html`);if(!response.ok){throw new Error(`Failed to load content: ${response.status}`);}
const html=await response.text();const tempDiv=document.createElement('div');tempDiv.innerHTML=html;const existingToc=tempDiv.querySelector('nav.table-of-contents');let tocResult=null;if(!existingToc){tocResult=generateTableOfContents(contentKey,html);if(tocResult&&tocResult.headingIds){const headings=tempDiv.querySelectorAll('h3, h4');tocResult.headingIds.forEach((item,index)=>{if(headings[index]){headings[index].id=item.id;}});}
if(tocResult){const firstHeading=tempDiv.querySelector('h1')||tempDiv.querySelector('h2');if(firstHeading){const tocDiv=document.createElement('div');tocDiv.innerHTML=tocResult.html;firstHeading.insertAdjacentElement('afterend',tocDiv.firstElementChild);}else{tempDiv.innerHTML=tocResult.html+tempDiv.innerHTML;}}}else{enhanceTOCWithNavigation(existingToc,contentKey);}
pageContent.innerHTML=tempDiv.innerHTML;displayHashtags(tempDiv);enableLazyLoading();if(typeof Prism!=='undefined'){Prism.highlightAllUnder(pageContent);}
if(typeof mermaid!=='undefined'){const mermaidBlocks=pageContent.querySelectorAll('pre.mermaid');if(mermaidBlocks.length>0){mermaid.run({nodes:mermaidBlocks,suppressErrors:true});}}
const tocContainer=pageContent.querySelector('.table-of-contents, nav.table-of-contents');if(tocContainer){const tocToggle=tocContainer.querySelector('.toc-toggle');const tocHeader=tocContainer.querySelector('.toc-header');if(tocToggle&&tocHeader){const tocState=sessionStorage.getItem(`toc-collapsed-${contentKey}`);if(tocState==='true'){tocContainer.classList.add('collapsed');}
tocToggle.addEventListener('click',function(e){e.stopPropagation();tocContainer.classList.toggle('collapsed');sessionStorage.setItem(`toc-collapsed-${contentKey}`,tocContainer.classList.contains('collapsed'));});tocHeader.addEventListener('click',function(e){if(tocContainer.classList.contains('collapsed')&&!e.target.closest('.toc-toggle')&&!e.target.closest('.toc-section-toggle')){tocContainer.classList.remove('collapsed');sessionStorage.setItem(`toc-collapsed-${contentKey}`,false);}});}
pageContent.querySelectorAll('.toc-section-toggle').forEach(toggle=>{toggle.addEventListener('click',function(e){e.stopPropagation();const section=this.closest('.toc-section');if(section){section.classList.toggle('collapsed');const sectionName=section.dataset.section;sessionStorage.setItem(`toc-section-${contentKey}-${sectionName}`,section.classList.contains('collapsed'));}});});pageContent.querySelectorAll('.toc-section').forEach(section=>{const sectionName=section.dataset.section;const sectionState=sessionStorage.getItem(`toc-section-${contentKey}-${sectionName}`);if(sectionState!==null){if(sectionState==='true'){section.classList.add('collapsed');}else{section.classList.remove('collapsed');}}});pageContent.querySelectorAll('.toc-item-wrapper').forEach(wrapper=>{wrapper.addEventListener('click',function(e){if(e.target.tagName==='A'){return;}
e.preventDefault();e.stopPropagation();const parentLi=this.closest('.toc-item');if(parentLi){parentLi.classList.toggle('collapsed');const itemLink=parentLi.querySelector('a');if(itemLink){const headingText=itemLink.textContent.trim();sessionStorage.setItem(`toc-heading-${contentKey}-${headingText}`,parentLi.classList.contains('collapsed'));}}});});pageContent.querySelectorAll('.toc-item').forEach(item=>{item.addEventListener('click',function(e){const rect=this.getBoundingClientRect();const clickX=e.clientX-rect.left;if(clickX>=0&&clickX<=24){e.preventDefault();e.stopPropagation();this.classList.toggle('collapsed');const itemLink=this.querySelector('a');if(itemLink){const headingText=itemLink.textContent.trim();sessionStorage.setItem(`toc-heading-${contentKey}-${headingText}`,this.classList.contains('collapsed'));}}});});pageContent.querySelectorAll('.toc-item').forEach(item=>{const itemLink=item.querySelector('a');const isSubpage=itemLink&&itemLink.hasAttribute('data-content');if(!isSubpage){const headingText=itemLink?itemLink.textContent.trim():'';const itemState=sessionStorage.getItem(`toc-heading-${contentKey}-${headingText}`);if(itemState==='true'){item.classList.add('collapsed');}}});pageContent.querySelectorAll('.table-of-contents a[data-content]').forEach(link=>{link.addEventListener('click',function(e){e.preventDefault();e.stopPropagation();const key=this.dataset.content;loadContent(key);expandToActiveItem(key);});});pageContent.querySelectorAll('.table-of-contents a:not([data-content]), nav.table-of-contents a:not([data-content])').forEach(link=>{link.addEventListener('click',function(e){e.preventDefault();e.stopPropagation();const href=this.getAttribute('href').substring(1);if(href.includes(':')){const[pageName,headingId]=href.split(':');window.location.hash=href;}else{const targetElement=document.getElementById(href);if(targetElement){targetElement.scrollIntoView({behavior:'smooth',block:'start'});window.location.hash=`${contentKey}:${href}`;}}});});}
pageContent.querySelectorAll('a[href^="#setup/"], a[href^="#content/"]').forEach(link=>{const href=link.getAttribute('href');if(href&&href.startsWith('#')){const contentKey=href.substring(1);link.setAttribute('data-content',contentKey);link.addEventListener('click',function(e){e.preventDefault();loadContent(contentKey);expandToActiveItem(contentKey);});}});pageContent.querySelectorAll('a[href^="#"]').forEach(link=>{const href=link.getAttribute('href');if(link.hasAttribute('data-content')||link.closest('.table-of-contents, nav.table-of-contents')){return;}
if(href.includes('/')){return;}
link.addEventListener('click',function(e){e.preventDefault();const anchorId=href.substring(1);if(anchorId.includes(':')){const[pageName,headingId]=anchorId.split(':');window.location.hash=anchorId;}else{const targetElement=document.getElementById(anchorId);if(targetElement){targetElement.scrollIntoView({behavior:'smooth',block:'start'});window.location.hash=`${contentKey}:${anchorId}`;}}});});currentContent=contentKey;updatePageMetadata(contentKey,tempDiv);if(updateHash){window.location.hash=contentKey;}
buildBreadcrumb(contentKey);if(saveToStorage){sessionStorage.setItem('currentPage',contentKey);}
document.querySelectorAll('#sidebar a').forEach(link=>{link.classList.remove('active');link.classList.remove('active-parent');});const activeLink=document.querySelector(`[data-content="${contentKey}"]`);if(activeLink&&activeLink.closest('#sidebar')){activeLink.classList.add('active');const topLevelParent=activeLink.closest('.nav-level-1 > li');if(topLevelParent){const topLevelLink=topLevelParent.querySelector(':scope > a, :scope > .nav-item-wrapper > a');if(topLevelLink&&topLevelLink!==activeLink){topLevelLink.classList.add('active-parent');}}}
setTimeout(()=>{const breadcrumbNav=document.getElementById('breadcrumb');if(breadcrumbNav){const breadcrumbItems=breadcrumbNav.querySelectorAll('li');if(breadcrumbItems.length>=2){const parentItem=breadcrumbItems[breadcrumbItems.length-2];const parentLink=parentItem.querySelector('a');if(parentLink){parentLink.focus();}else{const firstLink=breadcrumbNav.querySelector('a');if(firstLink)firstLink.focus();}}else if(breadcrumbItems.length===1){}}},100);}catch(error){console.error('Error loading content:',error);pageContent.innerHTML=`<h2>Error</h2><p>Failed to load content. Please try again.</p>`;currentContent=null;if(saveToStorage){sessionStorage.removeItem('currentPage');}}}
function getFirstNavigationItem(){const firstNavLink=document.querySelector('#sidebar .nav-level-1 > li:first-child a[data-content]');return firstNavLink?firstNavLink.dataset.content:'home';}
function getContentFromHash(){const hash=window.location.hash.slice(1);if(!hash)return null;if(hash.includes(':')){const[pageName,headingId]=hash.split(':');return{page:pageName,heading:headingId};}
return{page:hash,heading:null};}
function scrollToHeading(headingId){setTimeout(()=>{const headingElement=document.getElementById(headingId);if(headingElement){headingElement.scrollIntoView({behavior:'smooth',block:'start'});}},100);}
function toggleSubmenu(button){const parentLi=button.closest('.has-children');if(parentLi){parentLi.classList.toggle('expanded');saveExpandedState();}}
function saveExpandedState(){const expandedItems=[];document.querySelectorAll('.has-children.expanded > .nav-item-wrapper > a').forEach(link=>{if(link.dataset.content){expandedItems.push(link.dataset.content);}});sessionStorage.setItem('expandedMenuItems',JSON.stringify(expandedItems));}
function restoreExpandedState(){const savedExpanded=sessionStorage.getItem('expandedMenuItems');if(savedExpanded){try{const expandedItems=JSON.parse(savedExpanded);expandedItems.forEach(contentKey=>{const link=document.querySelector(`[data-content="${contentKey}"]`);if(link){const parentLi=link.closest('.has-children');if(parentLi){parentLi.classList.add('expanded');}}});}catch(e){console.error('Error restoring expanded state:',e);}}}
function expandToActiveItem(contentKey){const activeLink=document.querySelector(`[data-content="${contentKey}"]`);if(activeLink){let parentLi=activeLink.closest('li').parentElement.closest('.has-children');while(parentLi){parentLi.classList.add('expanded');parentLi=parentLi.parentElement.closest('.has-children');}
saveExpandedState();}}
document.addEventListener('DOMContentLoaded',async function(){const currentYear=new Date().getFullYear();const copyrightYearElement=document.getElementById('copyright-year');if(copyrightYearElement){copyrightYearElement.textContent=currentYear>2025?`-${currentYear}`:'';}
document.querySelectorAll('.nav-toggle').forEach(button=>{button.addEventListener('click',function(e){e.preventDefault();e.stopPropagation();toggleSubmenu(this);});});document.querySelectorAll('[data-content]').forEach(link=>{link.addEventListener('click',function(e){e.preventDefault();const contentKey=this.dataset.content;const parentLi=this.closest('li.has-children');if(parentLi){if(!parentLi.classList.contains('expanded')){parentLi.classList.add('expanded');saveExpandedState();}}
loadContent(contentKey);expandToActiveItem(contentKey);});});const hashResult=getContentFromHash();const savedPage=sessionStorage.getItem('currentPage');const firstNavItem=getFirstNavigationItem();const pageToLoad=hashResult?.page||savedPage||firstNavItem;const headingToScroll=hashResult?.heading;restoreExpandedState();await loadContent(pageToLoad,true,!hashResult);expandToActiveItem(pageToLoad);if(headingToScroll){scrollToHeading(headingToScroll);}
const sidebarToggle=document.getElementById('sidebar-toggle');const sidebar=document.getElementById('sidebar');const mainContainer=document.querySelector('.main-container');if(sidebarToggle&&sidebar&&mainContainer){const sidebarCollapsed=sessionStorage.getItem('sidebar-collapsed');if(sidebarCollapsed==='true'||window.innerWidth<=768){sidebar.classList.add('collapsed');mainContainer.classList.add('sidebar-collapsed');}
sidebarToggle.addEventListener('click',function(){sidebar.classList.toggle('collapsed');mainContainer.classList.toggle('sidebar-collapsed');const isCollapsed=sidebar.classList.contains('collapsed');sessionStorage.setItem('sidebar-collapsed',isCollapsed);});}});window.addEventListener('hashchange',function(){const hashResult=getContentFromHash();if(hashResult){loadContent(hashResult.page,true,false);expandToActiveItem(hashResult.page);if(hashResult.heading){scrollToHeading(hashResult.heading);}}else{const firstNavItem=getFirstNavigationItem();loadContent(firstNavItem);expandToActiveItem(firstNavItem);}});